//
//  ContentView.swift
//  Lollapalooza
//
//  Created by Lucas Cunha on 10/04/23.
//

import SwiftUI

var Taylor = Artist(name: "Taylor Swift", ProfileImage: "Taylor1", DescriptionImage: "Taylor2", Description: #"Taylor Alison Swift, born December 13th, 1989, is an american Singer-Songwriter famous for her narrative storytelling and confessional lyrics. Born in West Reading, Pennsylvania, she moved to Nashville, Tennessee to persue a carreer in music. Starting in country music, Swift began her journey with her self-titled album in 2006, she reached stardom with her next album's (Fearless) singles, "You Belong With Me" and "Love Story". After the second album acclaim, she adventured in a more pop oriented sound with her third and fourth albums, "Speak Now" and "Red". In 2014, she went full pop with the album "1989", which cimented her as a part of popular culure. She followed the tremedous sucess with "reputation", which told the story of her cancelation in the summer of 2016 and how her personal life and self-image was affected by the occurence. With singles like "Look what you made me do" and "End Game", Swift changed her sound from a maximalist pop to a more urban and dark atmosphere. In full contrast, "Lover", her next album was filled with songs with a happier and more energetic beats, seen in the singles "You Need To Call Down" and "Cruel Summmer". With the the Lover tour not being able to star, Swift changed her sound once more to fit the situation the world was facing. Her music became calmer, retrospective and folk-like in Folklore and Evermore, granting her a level of acclamation never seen before. Singles like "Cardigan" and "Willow" showed a different side of her to the public. Now, Swift has a new album returning to pop, "Midnights", but with a mixture of the folk sound she mastered in her previous work; and two of rerecordings of her previous works. Breaking records at every time she releases a new album, Taylor Swift has made herself part of the history of american music."# , Musics: [Music(title: "Anti-Hero", time: "3:24", image: "Taylor3"), Music(title: "Bejeweled", time: "3:15", image: "Taylor3"), Music(title: "Lavender Haze", time: "3:31", image: "Taylor3"), Music(title: "Midnight Rain", time: "2:59", image: "Taylor3")])

var FlorenceTheMachine = Artist(name: "Florence + The Machine", ProfileImage: "Florence1", DescriptionImage: "Florence2", Description: #"Florence + The Machine are an English indie rock band that formed in London in 2007, consisting of lead vocalist Florence Welch, keyboardist Isabella Summers, guitarist Rob Ackroyd, harpist Tom Monger, and a collaboration of other musicians. The band's music has received acclaim across the media, especially from the BBC, which played a large part in their rise to prominence by promoting Florence and the Machine as part of BBC Music Introducing. At the 2009 Brit Awards they received the Brit Awards "Critics' Choice" award. The band's music is renowned for its dramatic, eccentric production and Welch's powerful vocals.The band's debut studio album, Lungs, was released on 6 July 2009, and held the number-two position for its first five weeks on the UK Albums Chart. On 17 January 2010, the album reached the top position, after being on the chart for twenty-eight consecutive weeks. As of October 2010, the album had been in the top forty in the United Kingdom for sixty-five consecutive weeks, making it one of the best-selling albums of 2009 and 2010. The group's second studio album, Ceremonials, released in October 2011, entered the charts at number one in the UK and number six in the US. The band's third studio album, How Big, How Blue, How Beautiful, was released on 2 June 2015. It topped the UK charts, and debuted at number one on the US Billboard 200, their first to do so. The album reached number one in a total of eight countries and the top ten of twenty. Also in 2015, the band was the headlining act at Glastonbury Festival, making Welch the first British female headliner of the 21st century. Florence and the Machine's sound has been described as a combination of various genres, including rock and soul. Lungs (2009) won the Brit Award for Best British Album in 2010. Florence and the Machine have been nominated for six Grammy Awards including Best New Artist and Best Pop Vocal Album. Additionally, the band performed at the 2010 MTV Video Music Awards and the 2010 Nobel Peace Prize Concert."# , Musics:[Music(title: "King", time: "4:40", image: "Florence3"), Music(title: "Free", time: "3:55", image: "Florence3"), Music(title: "Choreomania", time: "3:33", image: "Florence3"), Music(title: "Back in Towm", time: "3:56", image: "Florence3")])

var Drake = Artist(name: "Drake", ProfileImage: "Drake1", DescriptionImage: "Drake2", Description: #"Drake, whose real name is Aubrey Drake Graham, is a Canadian rapper, singer, songwriter, actor, and entrepreneur. Born on October 24, 1986, in Toronto, Ontario, Drake first gained recognition for his role on the Canadian teen drama series "Degrassi: The Next Generation." As a musician, Drake has become one of the most successful artists of the 21st century. He has released several chart-topping albums, including "Thank Me Later," "Take Care," "Nothing Was the Same," "Views," and "Scorpion." He is known for his smooth flow, introspective lyrics, and ability to seamlessly blend different genres of music, including hip hop, R&B, and pop. Drake has also collaborated with numerous other artists, including Rihanna, Future, Lil Wayne, and Travis Scott. Some of his most popular songs include "Hotline Bling," "One Dance," "God's Plan," and "In My Feelings." In addition to his music career, Drake is also a successful entrepreneur. He founded the OVO Sound record label and clothing line, and has invested in several companies, including the e-sports organization 100 Thieves. Drake has won multiple Grammy Awards, Billboard Music Awards, and other honors throughout his career, and is widely regarded as one of the most influential musicians of his generation."#, Musics: [Music(title: "God's Plan", time: "3:18", image: "Drake3"), Music(title: "Jaded", time: "4:22", image: "Drake3"), Music(title: "In My Feelings", time: "3:37", image: "Drake3"),Music(title: "Finesse", time: "3:02", image: "Drake3"), Music(title: "That's How You Feel", time: "2:37", image: "Drake3")])

var BillieEilish = Artist(name: "Billie Eilish", ProfileImage: "Billie1", DescriptionImage: "Billie2", Description: #"Billie Eilish is an American singer, songwriter, and musician who rose to fame in 2015 with her debut single "Ocean Eyes." Born on December 18, 2001, in Los Angeles, California, Billie grew up in a family of musicians and was homeschooled along with her brother Finneas O'Connell, who is also a musician and producer. Billie's music is known for its haunting, introspective lyrics and minimalist, moody soundscapes that blend elements of pop, alternative, and electronic music. She often collaborates with her brother Finneas, who produces and co-writes many of her songs. Some of Billie's most popular songs include "bad guy," "bury a friend," "when the party's over," and "everything i wanted." She has won numerous awards, including multiple Grammy Awards, and is known for her unique sense of style, which often involves oversized clothing and bold hair colors. Billie has been open about her struggles with depression, anxiety, and Tourette syndrome, and has used her platform to raise awareness about mental health issues. She is also an advocate for environmental causes and has been vocal about the need for action on climate change."#, Musics: [Music(title: "Getting Older", time: "4:04", image: "Billie3"), Music(title: "Happier Than Ever", time: "4:58", image: "Billie3"), Music(title: "Therefore I am", time: "2:53", image: "Billie3"), Music(title: "Billie Bossa Nova", time: "3:16", image: "Billie3"), Music(title: "Everybody Dies", time: "3:26", image: "Billie3")])

var NaldoBenny = Artist(name: "Naldo Benny", ProfileImage: "Naldo1", DescriptionImage: "Naldo2", Description: "R&B e pop. Naldo disse que não se interessa pelo 'funk proibido', afirmando: 'Eu nem entro neste universo, acho que não precisa ser assim. Dá para fazer um som para cima, animado, com nível e sem perder a classe'. Ele cita Chris Brown e Kanye West como suas influências musicais.", Musics: [Music(title: "Amor de Chocolate", time: "3:38", image: "Naldo3"), Music(title: "Exagerado", time: "3:47", image: "Naldo3"), Music(title: "Chantilly", time: "3:50", image: "Naldo3"), Music(title: "Fogo", time: "3:35", image: "Naldo4"), Music(title: "Se Joga (feat Fat Joe)", time: "3:16", image: "Naldo3")])

var Jao = Artist(name: "Jão", ProfileImage: "Jao1", DescriptionImage: "Jao2", Description: "João Vitor Romania Balbino (Américo Brasiliense, 3 de novembro de 1994), mais conhecido pelo seu nome artístico Jão, é um cantor e compositor brasileiro. Ele começou sua carreira musical em 2016, postando covers de canções no aplicativo de compartilhamento de vídeos YouTube. Entre seus prêmios, Jão ganhou três MTV Miaw Brasil, um Troféu Imprensa e um Internet e recebeu duas indicações ao Grammy Latino e sete ao Prêmio Multishow de Música Brasileira.", Musics: [Music(title: "Pilantra", time: "3:12", image: "Jao3"), Music(title: "Idiota", time: "3:01", image: "Jao4"), Music(title: "Essa Eu Fiz Pro Nosso Amor", time: "3:14", image: "Jao5"), Music(title: "Meninos e Meninas", time: "2:41", image: "Jao4"), Music(title: "Santo", time: "2:42", image: "Jao4")])

var Ed = Artist(name: "Ed Sheeran", ProfileImage: "Ed1", DescriptionImage: "Ed2", Description: "Edward Christopher Sheeran MBE, mais conhecido como Ed Sheeran (Halifax, 17 de fevereiro de 1991) é um cantor, compositor, produtor e ator britânico.  Ele se casou com Cherry Seaborn em janeiro de 2019 e hoje o casal tem duas filhas chamadas Lyra Antarctica Seaborn Sheeran e Jupiter Seaborn Sheeran. No início de 2012, Sheeran lançou um extended play independente, que chamou a atenção de Elton John e Jamie Foxx. Ele, em seguida, assinou contrato com a Asylum Records. Seu álbum de estréia, + (plus) (2011), contendo os singles 'The A Team', 'You Need Me, I Don't Need You', 'Lego House' e 'Drunk' foi disco de platina quíntuplo no Reino Unido. Em 2012, ele ganhou dois Brit Awards para Melhor Artista Solo Britânico Masculino e Breakthrough Act britânico. 'The A Team' ganhou o prêmio Ivor Novello de Melhor Canção Musicalmente e liricamente. Em 2014 ele foi nomeado para Best New Artist na 56ª Annual Grammy Awards.", Musics: [Music(title: "Shape Of You",time: "3:53",image: "Ed3"), Music(title: "Eraser",time: "3:47",image: "Ed3"), Music(title: "Castle on the Hill",time: "4:21",image: "Ed3"), Music(title: "Perfect",time: "4:23",image: "Ed3"), Music(title: "Barcelona",time: "3:10",image: "Ed3")])

var Harry = Artist(name: "Harry Styles", ProfileImage: "Harry1", DescriptionImage: "Harry2", Description:"Harry Edward Styles (Redditch, 1 de fevereiro de 1994) é um cantor, compositor e ator britânico. Sua carreira musical começou em 2010 como concorrente solo na série britânica de competição de música The X Factor. Após sua eliminação, ele foi trazido de volta para se juntar à boy band One Direction, que se tornou uma das boy bands mais vendidas de todos os tempos antes de entrar em um hiato indefinido em 2016. Styles lançou seu álbum solo de estreia autointitulado pela Columbia Records em 2017. Ele estreou no número um no Reino Unido e nos EUA e foi um dos dez álbuns mais vendidos do mundo no ano, enquanto seu primeiro single, 'Sign of the Times', liderou a UK Singles Chart. O segundo álbum de Styles, Fine Line (2019), estreou no topo da Billboard 200 dos EUA com a maior estreia de um artista masculino britânico, e foi o álbum mais recente a ser incluído nos '500 Maiores Álbuns de Todos os Tempos' da Rolling Stone em 2020. Seu quarto single, 'Watermelon Sugar', liderou a Billboard Hot 100 dos EUA. Apresentando o single do topo das paradas 'As It Was', o terceiro álbum de Styles, Harry's House (2022), foi amplamente aclamado e quebrou vários recordes.", Musics: [Music(title: "As It Was",time: "2:47",image: "Harry3"), Music(title: "Keep Driving",time: "2:20",image: "Harry3"), Music(title: "Late Night Talking",time: "2:57",image: "Harry3"), Music(title: "Grapejuice",time: "3:11",image: "Harry3"), Music(title: "Boyfriends",time: "3:14",image: "Harry3")])

var Artists: [Artist] = [Taylor, FlorenceTheMachine, Drake, BillieEilish, NaldoBenny, Jao, Ed, Harry]

struct ContentView: View {
    var body: some View {
        VStack {
            Image(systemName: "globe")
                .imageScale(.large)
                .foregroundColor(.accentColor)
            Text("Hello, world!")
        }
        .padding()
    }
}

struct ContentView_Previews: PreviewProvider {
    static var previews: some View {
        ContentView()
    }
}
